-- Ratchet test: inventories every _G.QUI_* assignment site in core/, modules/,
-- QUI_*/, and init.lua. Fails CI when a new site appears without updating the
-- approved inventory. The inventory may only SHRINK as sites are migrated to
-- ns.*, ns.Registry, or ns.QUI_Modules.
--
-- Plain Lua 5.1, file-driven (no harness). Run from repo root:
--   lua tests/unit/global_assignment_ratchet_test.lua          -- verify
--   lua tests/unit/global_assignment_ratchet_test.lua --update -- regenerate inventory

local updateMode = (arg and arg[1] == "--update")

local failures = 0
local function check(name, ok, detail)
    if ok then
        print(("  ok  %s"):format(name))
    else
        failures = failures + 1
        print(("FAIL  %s  %s"):format(name, detail or ""))
    end
end

-- ---------------------------------------------------------------------------
-- File enumeration via git ls-files
-- ---------------------------------------------------------------------------
local function listInScopeFiles()
    local files = {}
    local p = io.popen and io.popen('git ls-files "*.lua"')
    if p then
        for line in p:lines() do
            -- Keep only core/, modules/, QUI_*/, and init.lua at repo root.
            if line:match("^core/")
                or line:match("^modules/")
                or line:match("^QUI_[^/]+/")
                or line == "init.lua"
            then
                files[#files + 1] = line
            end
        end
        p:close()
    end
    return files
end

-- ---------------------------------------------------------------------------
-- Scan a source file for _G.QUI_<Name> = ... (excluding ==)
-- Returns a deduplicated array of "<path>::<name>" strings.
-- ---------------------------------------------------------------------------
local function scanFile(path)
    local fh = io.open(path, "r")
    if not fh then return {} end
    local seen = {}
    local sites = {}
    for line in fh:lines() do
        -- Match _G.QUI_<word> = where the char after = is not another =
        local name = line:match("_G%.QUI_([%w_]+)%s*=[^=]")
        if name and not seen[name] then
            seen[name] = true
            sites[#sites + 1] = path .. "::" .. "QUI_" .. name
        end
    end
    fh:close()
    return sites
end

-- ---------------------------------------------------------------------------
-- Collect all sites
-- ---------------------------------------------------------------------------
local function collectAllSites()
    local files = listInScopeFiles()
    local allSites = {}
    for _, path in ipairs(files) do
        local sites = scanFile(path)
        for _, site in ipairs(sites) do
            allSites[#allSites + 1] = site
        end
    end
    table.sort(allSites)
    return allSites
end

-- ---------------------------------------------------------------------------
-- --update mode: regenerate tests/unit/global_assignment_inventory.lua
-- ---------------------------------------------------------------------------
if updateMode then
    local sites = collectAllSites()
    local out = io.open("tests/unit/global_assignment_inventory.lua", "w")
    if not out then
        print("FAIL  could not open tests/unit/global_assignment_inventory.lua for writing")
        os.exit(1)
    end
    out:write("-- GENERATED by global_assignment_ratchet_test.lua --update; do not hand-edit.\n")
    out:write("-- One line per _G.QUI_* assignment site.\n")
    out:write("-- This list may only shrink — new cross-module APIs go on ns.*\n")
    out:write("return {\n")
    for _, site in ipairs(sites) do
        out:write(('    "%s",\n'):format(site))
    end
    out:write("}\n")
    out:close()
    print(("OK: global_assignment_ratchet_test --update wrote %d sites"):format(#sites))
    os.exit(0)
end

-- ---------------------------------------------------------------------------
-- Verify mode: compare current scan against inventory
-- ---------------------------------------------------------------------------
local inventoryPath = "tests/unit/global_assignment_inventory.lua"
local inventoryFn, loadErr = loadfile(inventoryPath)
if not inventoryFn then
    print("FAIL  cannot load inventory: " .. tostring(loadErr))
    print("      Run: lua tests/unit/global_assignment_ratchet_test.lua --update")
    os.exit(1)
end
local inventoryList = inventoryFn()
if type(inventoryList) ~= "table" then
    print("FAIL  inventory did not return a table")
    os.exit(1)
end

local inventorySet = {}
for _, site in ipairs(inventoryList) do
    inventorySet[site] = true
end

local foundSites = collectAllSites()
local foundSet = {}
for _, site in ipairs(foundSites) do
    foundSet[site] = true
end

-- New sites (found but not listed)
local newSites = {}
for _, site in ipairs(foundSites) do
    if not inventorySet[site] then
        newSites[#newSites + 1] = site
    end
end

-- Stale entries (listed but not found)
local staleSites = {}
for _, site in ipairs(inventoryList) do
    if not foundSet[site] then
        staleSites[#staleSites + 1] = site
    end
end

for _, site in ipairs(newSites) do
    check("no new _G.QUI_* assignment site: " .. site, false,
        "new _G.QUI_* assignment site: " .. site
        .. " — export on ns.* (see bootstrap proxy), register refresh via ns.Registry,"
        .. " or events via ns.QUI_Modules. If this _G global is genuinely required"
        .. " (external addon contract), run:"
        .. " lua tests/unit/global_assignment_ratchet_test.lua --update"
        .. " and justify the inventory diff in review.")
end

for _, site in ipairs(staleSites) do
    check("no stale inventory entry: " .. site, false,
        "stale inventory — run --update")
end

if #newSites == 0 and #staleSites == 0 then
    check("inventory matches source", true)
end

print(("OK: global_assignment_ratchet_test (%d sites)"):format(#foundSites))
os.exit(failures == 0 and 0 or 1)
