local env = dofile("tests/helpers/character_chrome_harness.lua").Build()
local file = assert(io.open(os.getenv("QUI_OBJECTIVE_SOURCE") or "modules/skinning/gameplay/objectivetracker.lua"))
local source = file:read("*a")
file:close()
local first = assert(source:find("local function ApplyBackdropColors(", 1, true))
local last = assert(source:find("local function ApplyQUIBackdrop(", first, true))
local chunk = assert(loadstring(source:sub(first, last - 1) .. "\nreturn ApplyBackdropColors"))
setfenv(chunk, setmetatable({ SkinBase = env.SkinBase }, { __index = _G }))
local apply = chunk()
local frame = env.NewFrame("Frame")
apply(frame, false, .2, .3, .4, 1, .05, .06, .07, .45)
local surface = frame._quiRoundedSurface
assert(surface and surface.radius == 8, "tracker background must match the rounded window shell")
assert(surface.background.color[4] == .45, "tracker must preserve configured background opacity")
apply(frame, true, .2, .3, .4, 1, .05, .06, .07, .25)
assert(surface.borderPixels == 0, "hide-border option must remove the physical border")
assert(surface.background.color[4] == .25, "opacity updates must persist on the same rounded surface")
print("OK: objectivetracker_rounded_background_test")
