-- Ratchet test: per-file inventory of bare `pcall(` call sites in core/,
-- modules/, QUI_*/, and init.lua. Replaces the retired 2026-07 safecall
-- migration pin wave (options_safecall_migration, safecall_swallow_t1*,
-- safecall_redundant_removal_t2, safecall_bulkhead_t3, safecall_migration_t45*,
-- consumablecheck_pcall_removal): those proved the one-time conversion; this
-- guards the steady state. Fails CI when a file's pcall count changes without
-- updating the inventory.
--
-- A pcall count going UP is usually wrong: error-swallowing dispatch belongs in
-- ns.SafeCall (core/safecall.lua). Legitimate new pcalls exist — secret-value
-- probe reads (probe before ANY truth-test) and checked-result pcalls whose
-- ok/err is actually consumed — and for those you update the inventory and
-- justify the diff in review.
--
-- Counts are raw text matches (comments included), which keeps the scan exact
-- and deterministic; a commented-out pcall still forces a deliberate --update.
-- The frontier pattern does not match xpcall.
--
-- Plain Lua 5.1, file-driven (no harness). Run from repo root:
--   lua tests/unit/pcall_site_ratchet_test.lua          -- verify
--   lua tests/unit/pcall_site_ratchet_test.lua --update -- regenerate inventory

local updateMode = (arg and arg[1] == "--update")

local failures = 0
local function check(name, ok, detail)
    if ok then
        print(("  ok  %s"):format(name))
    else
        failures = failures + 1
        print(("FAIL  %s  %s"):format(name, detail or ""))
    end
end

-- ---------------------------------------------------------------------------
-- File enumeration via git ls-files (same scope as global_assignment_ratchet)
-- ---------------------------------------------------------------------------
local function listInScopeFiles()
    local files = {}
    local p = io.popen and io.popen('git ls-files "*.lua"')
    if p then
        for line in p:lines() do
            if line:match("^core/")
                or line:match("^modules/")
                or line:match("^QUI_[^/]+/")
                or line == "init.lua"
            then
                files[#files + 1] = line
            end
        end
        p:close()
    end
    return files
end

-- ---------------------------------------------------------------------------
-- Count bare pcall( sites in one file. %f[%w_] rejects xpcall.
-- ---------------------------------------------------------------------------
local function countFile(path)
    local fh = io.open(path, "r")
    if not fh then return 0 end
    local src = fh:read("*a")
    fh:close()
    local n = 0
    for _ in src:gmatch("%f[%w_]pcall%s*%(") do
        n = n + 1
    end
    return n
end

-- ---------------------------------------------------------------------------
-- Collect "path::count" for every in-scope file with at least one site
-- ---------------------------------------------------------------------------
local function collectAllCounts()
    local entries, byPath = {}, {}
    for _, path in ipairs(listInScopeFiles()) do
        local n = countFile(path)
        if n > 0 then
            entries[#entries + 1] = ("%s::%d"):format(path, n)
            byPath[path] = n
        end
    end
    table.sort(entries)
    return entries, byPath
end

local INVENTORY_PATH = "tests/helpers/pcall_site_inventory.lua"

-- ---------------------------------------------------------------------------
-- --update mode: regenerate the inventory
-- ---------------------------------------------------------------------------
if updateMode then
    local entries = collectAllCounts()
    local out = io.open(INVENTORY_PATH, "w")
    if not out then
        print("FAIL  could not open " .. INVENTORY_PATH .. " for writing")
        os.exit(1)
    end
    out:write("-- GENERATED by pcall_site_ratchet_test.lua --update; do not hand-edit.\n")
    out:write("-- One line per in-scope file containing bare pcall( sites: \"path::count\".\n")
    out:write("-- Error-swallowing dispatch goes through ns.SafeCall; a count increase is\n")
    out:write("-- only for secret-probe reads or checked-result pcalls, justified in review.\n")
    out:write("return {\n")
    for _, entry in ipairs(entries) do
        out:write(('    "%s",\n'):format(entry))
    end
    out:write("}\n")
    out:close()
    print(("OK: pcall_site_ratchet_test --update wrote %d files"):format(#entries))
    os.exit(0)
end

-- ---------------------------------------------------------------------------
-- Verify mode: exact match against the inventory, per file
-- ---------------------------------------------------------------------------
local inventoryFn, loadErr = loadfile(INVENTORY_PATH)
if not inventoryFn then
    print("FAIL  cannot load inventory: " .. tostring(loadErr))
    print("      Run: lua tests/unit/pcall_site_ratchet_test.lua --update")
    os.exit(1)
end
local inventoryList = inventoryFn()
if type(inventoryList) ~= "table" then
    print("FAIL  inventory did not return a table")
    os.exit(1)
end

local inventoryByPath = {}
for _, entry in ipairs(inventoryList) do
    local path, n = entry:match("^(.-)::(%d+)$")
    if path then inventoryByPath[path] = tonumber(n) end
end

local _, foundByPath = collectAllCounts()

local paths, seen = {}, {}
for path in pairs(inventoryByPath) do
    if not seen[path] then seen[path] = true; paths[#paths + 1] = path end
end
for path in pairs(foundByPath) do
    if not seen[path] then seen[path] = true; paths[#paths + 1] = path end
end
table.sort(paths)

local mismatches = 0
for _, path in ipairs(paths) do
    local want, got = inventoryByPath[path], foundByPath[path] or 0
    if want == nil then
        mismatches = mismatches + 1
        check("pcall count: " .. path, false,
            ("new file with %d bare pcall site(s) — route error-swallowing"
            .. " dispatch through ns.SafeCall (core/safecall.lua); if these are"
            .. " secret probes or checked-result pcalls, run"
            .. " lua tests/unit/pcall_site_ratchet_test.lua --update"
            .. " and justify the inventory diff in review."):format(got))
    elseif got > want then
        mismatches = mismatches + 1
        check("pcall count: " .. path, false,
            ("%d -> %d — new bare pcall site(s); use ns.SafeCall for"
            .. " error-swallowing dispatch, or --update + review justification"
            .. " for probes/checked-result pcalls."):format(want, got))
    elseif got < want then
        mismatches = mismatches + 1
        check("pcall count: " .. path, false,
            ("%d -> %d — sites removed; lock in the shrink with"
            .. " lua tests/unit/pcall_site_ratchet_test.lua --update"):format(want, got))
    end
end

if mismatches == 0 then
    check("inventory matches source", true)
end

local total = 0
for _, n in pairs(foundByPath) do total = total + n end
print(("OK: pcall_site_ratchet_test (%d sites)"):format(total))
os.exit(failures == 0 and 0 or 1)
