-- tests/unit/search_cache_generated_banner_test.lua
-- Run: lua tests/unit/search_cache_generated_banner_test.lua

local function readAll(path)
    local file = assert(io.open(path, "rb"))
    local data = file:read("*a")
    file:close()
    return (data:gsub("\r\n", "\n"))
end

local cache = readAll("QUI_OptionsSearch/search_cache.lua")
local generator = readAll("tools/generate_search_cache.lua")

local banner = "-- Generated by tools/generate_search_cache.lua; do not edit by hand."

assert(cache:sub(1, #banner) == banner,
    "generated search cache must start with generated-file banner")
assert(generator:find(banner, 1, true),
    "generator must emit the generated-file banner")

print("OK: search_cache_generated_banner_test")
