local env = dofile("tools/_addon_env.lua")
local ns = env.LoadCore()
local H = ns.Helpers

assert(H.FoldUTF8("AbC") == "abc", "ascii fold")
assert(H.FoldUTF8("МОСКВА") == "москва", "cyrillic A-P fold")
assert(H.FoldUTF8("РЫБА") == "рыба", "cyrillic R-Ya fold crosses lead byte")
assert(H.FoldUTF8("Ёлка") == "ёлка", "io fold")
assert(H.FoldUTF8("Зелёная Роща") == "зелёная роща", "mixed cyrillic fold")
assert(H.FoldUTF8("ÀÉÎÕÜ") == "àéîõü", "latin-1 fold")
assert(H.FoldUTF8("ØSE") == "øse", "latin-1 upper tail fold")
assert(H.FoldUTF8("Œuvre") == "œuvre", "oe ligature fold")
assert(H.FoldUTF8("3×4") == "3×4", "multiplication sign untouched")
assert(H.FoldUTF8("日本語テキスト") == "日本語テキスト", "cjk untouched")
assert(H.FoldUTF8("한국어") == "한국어", "hangul untouched")
assert(H.FoldUTF8(nil) == "", "nil folds to empty")
assert(H.UpperUTF8("москва") == "МОСКВА", "cyrillic upper")
assert(H.UpperUTF8("рыба") == "РЫБА", "cyrillic upper crosses lead byte")
assert(H.UpperUTF8("ёлка") == "ЁЛКА", "io upper")
assert(H.UpperUTF8("àéîõü") == "ÀÉÎÕÜ", "latin-1 upper")
assert(H.UpperUTF8("œuvre") == "ŒUVRE", "oe ligature upper")
assert(H.UpperUTF8("straße") == "STRAßE", "sharp s deliberately not uppercased")

print("ok utf8 fold/upper")
