---@meta
-- WoW globals (UI frames, font objects, constants, legacy functions) the
-- addon references, declared opaque so they resolve without per-symbol
-- signatures. AUTO-GENERATED by tools/generate_lua_definitions.lua from the
-- No supplemental globals configured.

